/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsNewRouteImport } from './routes/whats-new'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists/index'
import { Route as PlaylistsPlaylistIdRouteImport } from './routes/playlists/$playlistId'
import { Route as FavoritesTracksRouteImport } from './routes/favorites/tracks'
import { Route as FavoritesArtistsRouteImport } from './routes/favorites/artists'
import { Route as FavoritesAlbumsRouteImport } from './routes/favorites/albums'
import { Route as PlaylistsImportProviderIdRouteImport } from './routes/playlists/import/$providerId'
import { Route as ArtistProviderIdArtistIdRouteImport } from './routes/artist/$providerId/$artistId'
import { Route as AlbumProviderIdAlbumIdRouteImport } from './routes/album/$providerId/$albumId'

const WhatsNewRoute = WhatsNewRouteImport.update({
  id: '/whats-new',
  path: '/whats-new',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsPlaylistIdRoute = PlaylistsPlaylistIdRouteImport.update({
  id: '/playlists/$playlistId',
  path: '/playlists/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesTracksRoute = FavoritesTracksRouteImport.update({
  id: '/favorites/tracks',
  path: '/favorites/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesArtistsRoute = FavoritesArtistsRouteImport.update({
  id: '/favorites/artists',
  path: '/favorites/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesAlbumsRoute = FavoritesAlbumsRouteImport.update({
  id: '/favorites/albums',
  path: '/favorites/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsImportProviderIdRoute =
  PlaylistsImportProviderIdRouteImport.update({
    id: '/playlists/import/$providerId',
    path: '/playlists/import/$providerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArtistProviderIdArtistIdRoute =
  ArtistProviderIdArtistIdRouteImport.update({
    id: '/artist/$providerId/$artistId',
    path: '/artist/$providerId/$artistId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlbumProviderIdAlbumIdRoute = AlbumProviderIdAlbumIdRouteImport.update({
  id: '/album/$providerId/$albumId',
  path: '/album/$providerId/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/logs': typeof LogsRoute
  '/plugins': typeof PluginsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/themes': typeof ThemesRoute
  '/whats-new': typeof WhatsNewRoute
  '/favorites/albums': typeof FavoritesAlbumsRoute
  '/favorites/artists': typeof FavoritesArtistsRoute
  '/favorites/tracks': typeof FavoritesTracksRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/album/$providerId/$albumId': typeof AlbumProviderIdAlbumIdRoute
  '/artist/$providerId/$artistId': typeof ArtistProviderIdArtistIdRoute
  '/playlists/import/$providerId': typeof PlaylistsImportProviderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/logs': typeof LogsRoute
  '/plugins': typeof PluginsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/themes': typeof ThemesRoute
  '/whats-new': typeof WhatsNewRoute
  '/favorites/albums': typeof FavoritesAlbumsRoute
  '/favorites/artists': typeof FavoritesArtistsRoute
  '/favorites/tracks': typeof FavoritesTracksRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/album/$providerId/$albumId': typeof AlbumProviderIdAlbumIdRoute
  '/artist/$providerId/$artistId': typeof ArtistProviderIdArtistIdRoute
  '/playlists/import/$providerId': typeof PlaylistsImportProviderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/logs': typeof LogsRoute
  '/plugins': typeof PluginsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/themes': typeof ThemesRoute
  '/whats-new': typeof WhatsNewRoute
  '/favorites/albums': typeof FavoritesAlbumsRoute
  '/favorites/artists': typeof FavoritesArtistsRoute
  '/favorites/tracks': typeof FavoritesTracksRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/album/$providerId/$albumId': typeof AlbumProviderIdAlbumIdRoute
  '/artist/$providerId/$artistId': typeof ArtistProviderIdArtistIdRoute
  '/playlists/import/$providerId': typeof PlaylistsImportProviderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/logs'
    | '/plugins'
    | '/search'
    | '/settings'
    | '/sources'
    | '/themes'
    | '/whats-new'
    | '/favorites/albums'
    | '/favorites/artists'
    | '/favorites/tracks'
    | '/playlists/$playlistId'
    | '/playlists/'
    | '/album/$providerId/$albumId'
    | '/artist/$providerId/$artistId'
    | '/playlists/import/$providerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/logs'
    | '/plugins'
    | '/search'
    | '/settings'
    | '/sources'
    | '/themes'
    | '/whats-new'
    | '/favorites/albums'
    | '/favorites/artists'
    | '/favorites/tracks'
    | '/playlists/$playlistId'
    | '/playlists'
    | '/album/$providerId/$albumId'
    | '/artist/$providerId/$artistId'
    | '/playlists/import/$providerId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/logs'
    | '/plugins'
    | '/search'
    | '/settings'
    | '/sources'
    | '/themes'
    | '/whats-new'
    | '/favorites/albums'
    | '/favorites/artists'
    | '/favorites/tracks'
    | '/playlists/$playlistId'
    | '/playlists/'
    | '/album/$providerId/$albumId'
    | '/artist/$providerId/$artistId'
    | '/playlists/import/$providerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LogsRoute: typeof LogsRoute
  PluginsRoute: typeof PluginsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  ThemesRoute: typeof ThemesRoute
  WhatsNewRoute: typeof WhatsNewRoute
  FavoritesAlbumsRoute: typeof FavoritesAlbumsRoute
  FavoritesArtistsRoute: typeof FavoritesArtistsRoute
  FavoritesTracksRoute: typeof FavoritesTracksRoute
  PlaylistsPlaylistIdRoute: typeof PlaylistsPlaylistIdRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
  AlbumProviderIdAlbumIdRoute: typeof AlbumProviderIdAlbumIdRoute
  ArtistProviderIdArtistIdRoute: typeof ArtistProviderIdArtistIdRoute
  PlaylistsImportProviderIdRoute: typeof PlaylistsImportProviderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whats-new': {
      id: '/whats-new'
      path: '/whats-new'
      fullPath: '/whats-new'
      preLoaderRoute: typeof WhatsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$playlistId': {
      id: '/playlists/$playlistId'
      path: '/playlists/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof PlaylistsPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites/tracks': {
      id: '/favorites/tracks'
      path: '/favorites/tracks'
      fullPath: '/favorites/tracks'
      preLoaderRoute: typeof FavoritesTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites/artists': {
      id: '/favorites/artists'
      path: '/favorites/artists'
      fullPath: '/favorites/artists'
      preLoaderRoute: typeof FavoritesArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites/albums': {
      id: '/favorites/albums'
      path: '/favorites/albums'
      fullPath: '/favorites/albums'
      preLoaderRoute: typeof FavoritesAlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/import/$providerId': {
      id: '/playlists/import/$providerId'
      path: '/playlists/import/$providerId'
      fullPath: '/playlists/import/$providerId'
      preLoaderRoute: typeof PlaylistsImportProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$providerId/$artistId': {
      id: '/artist/$providerId/$artistId'
      path: '/artist/$providerId/$artistId'
      fullPath: '/artist/$providerId/$artistId'
      preLoaderRoute: typeof ArtistProviderIdArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$providerId/$albumId': {
      id: '/album/$providerId/$albumId'
      path: '/album/$providerId/$albumId'
      fullPath: '/album/$providerId/$albumId'
      preLoaderRoute: typeof AlbumProviderIdAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LogsRoute: LogsRoute,
  PluginsRoute: PluginsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  ThemesRoute: ThemesRoute,
  WhatsNewRoute: WhatsNewRoute,
  FavoritesAlbumsRoute: FavoritesAlbumsRoute,
  FavoritesArtistsRoute: FavoritesArtistsRoute,
  FavoritesTracksRoute: FavoritesTracksRoute,
  PlaylistsPlaylistIdRoute: PlaylistsPlaylistIdRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
  AlbumProviderIdAlbumIdRoute: AlbumProviderIdAlbumIdRoute,
  ArtistProviderIdArtistIdRoute: ArtistProviderIdArtistIdRoute,
  PlaylistsImportProviderIdRoute: PlaylistsImportProviderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
